# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
#registries:
#  github-glfw:
#    type: git
#    url: https://github.com/glfw/glfw.git
#    username: Weydon-Ding
#    password: ${{secrets.MY_ARTIFACTORY_PASSWORD}}
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  #- package-ecosystem: "gitsubmodule" # See documentation for possible values
  #  directory: "/" # Location of package manifests
  #  registries:
  #    - github-glfw
  #  schedule:
  #    interval: "monthly"
